# Generated by Django 3.0.6 on 2020-12-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_CandyMuebles', '0002_auto_20201215_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='status',
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('idpedidodetalle', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('fecha_ini', models.DateField(blank=True, db_column='Fecha Inicio', null=True)),
                ('fecha_fin', models.DateField(blank=True, db_column='Fecha Fin', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=2, null=True)),
                ('pedido_idpedido', models.ForeignKey(db_column='Pedido_idpedido', on_delete=django.db.models.deletion.CASCADE, to='mi_CandyMuebles.Pedido')),
                ('producto_idproducto', models.ForeignKey(db_column='Producto_idproducto', on_delete=django.db.models.deletion.CASCADE, to='mi_CandyMuebles.Producto')),
            ],
            options={
                'db_table': 'PedidoDetalle',
                'managed': True,
                'unique_together': {('idpedidodetalle', 'pedido_idpedido', 'producto_idproducto')},
            },
        ),
    ]
