# Generated by Django 3.0.6 on 2020-12-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_CandyMuebles', '0003_auto_20201217_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='idpedidodetalle',
            field=models.AutoField(db_column='idpedidodetalle', primary_key=True, serialize=False),
        ),
    ]
