# Generated by Django 3.0.6 on 2020-12-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_CandyMuebles', '0004_auto_20201217_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, db_column='Stock', null=True),
        ),
    ]
